apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
        - name: gitops-app
          image: walidbannouri/gitops-app:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: MONGO_URI
          ports:
            - containerPort: 3000
