apiVersion: v1
kind: Service
metadata:
  name: gitops-app-svc
  namespace: myapp
spec:
  selector:
    app: gitops-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort